---
title: "Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load('data/03-results-text.RData')
#load('data/04-results-text.RData')
load('data/05-results-text.RData')
#load('data/06-results-text.RData')
```

## Mapping local relative contributions for single- and multi-species comparisons

#### Results for Alburnoides bipunctatus

The spatial distribution of *Alburnoides bipunctatus* exhibited highest occurrence in the lower elevation main stem of the Aare river and the adjoining tributaries (Figure 1a). River discharge, connectivity, and temperature were the most important environmental factors contributing to environmental suitability (Figure 1b-c). The remaining factors of urbanisation, river morphological modification index, distance to lakes, floodplain availability and flow velocity had lower contributions. Investigating the spatial distribution of Shapely values revealed independent contributions of variables to the spatial distribution of environmental suitability of *A. bipunctatus* (Figure 1d-k, and across all species Figure S2-S9). For example, river discharge and connectivity had spatially independent contributions to environmental suitability, even though these variables had similarly high overall importance (Spearman's rank correlation, ρ = `r cor_discharge_connectivity`). We found low spatial correlations between all pairwise comparisons of Shapley values across all variables for *A. bipunctatus* (\|median Spearman's rank correlation\| = `r cor_median_abs_all`, \|mean\|= `r cor_mean_sd_all`). This independence between Shapely values for different variables was generated by initial differences in the spatial variation in the raw environmental factors (Figure S10) combined with the different effect of each environmental factor on environmental suitability of *A. bipunctatus* in terms of magnitude, direction, and response shape (i.e., different sensitivity to different factors; insets in Figure 1d-k).

**Results across all species**

no exact values used

## Deconstructing distributions to build conservation expectations

Overall, a wide range of the areas within the natural abiotic niche of *A. bipunctatus* had negative Shapely values for threats, in other words, *A. bipunctatus* had a large shadow distribution (Figure 4). First partitioning the Shapley values to identify areas where natural factors support *A. bipunctatus* revealed a high percentage of sub-catchments had positive contributions of discharge (`r AB_shad_summary[3,'value']`%), minimum temperature (`r AB_shad_summary[4,'value']`%), flow velocity (`r AB_shad_summary[6,'value']`%) and proximity to lakes (`r AB_shad_summary[7,'value']`%) to environmental suitability. However, the area of geographic distribution within the abiotic niche dropped dramatically when we considered all natural factors together in contrast to independently, and this "expected distribution" was only `r AB_shad_summary[1,'value']`% of all sub-catchments (i.e., defined as sub-catchments with positive contribution across the sum of natural abiotic Shapley values; Figure 4a-b). Furthermore, only `r AB_shad_summary[2,'value']`% of all sub-catchments had positive contributions for every individual natural abiotic factors.

Next, we investigated anthropogenic threats within the expected distribution, finding that in `r AB_shad_summary[17,'value']`% of *A. bipunctatus's* expected distribution there was at least one threat with a negative contribution to environmental suitability (one threat in `r AB_shad_summary[13,'value']`% areas, two in `r AB_shad_summary[14,'value']`%, three in `r AB_shad_summary[15,'value']`% and four in `r AB_shad_summary[16,'value']`%). Within the expected distribution, we summed all potential positive and negative threat effects and found a net negative effect of threats in `r AB_shad_summary[18,'value']`% sub-catchments. In sub-catchments with at least one threat, we also found a `r AB_shad_summary[21,'value']`% reduction in environmental suitability. Consequently, within the expected distribution the rate of predicted absence was `r AB_shad_summary[24,'value']` times higher in threatened (`r AB_shad_summary[23,'value']`% absent) compared to unthreatened (`r AB_shad_summary[22,'value']`% absent) sub-catchments (Figure 4c-d). Importantly, while connectivity was overall the most important threat variable in our model (Figure 1b) much of the negative impact is outside of the natural abiotic niche of the species so only `r AB_shad_summary[11,'value']`% of the expected distribution was negatively impacted by connectivity. Similarly, we found the opposite for habitat variables which had lower importance in our models but with negative contributions to environmental suitability across a larger percentage the expected distribution (e.g., high river morphological modification index = `r AB_shad_summary[10,'value']`%%, low floodplain cover = `r AB_shad_summary[8,'value']`% and high urbanisation = `r AB_shad_summary[9,'value']`%; Figure 4). These single species results were highly consistent when assessed across all species independently, with an average of `r paste0(signif(summary_shadow_mean[22,'mean'],2),' ± ', round(summary_shadow_mean[22,'sd']))`% sub-catchments inside species' niche having a negative contribution of at least one threat, and `r paste0(signif(summary_shadow_mean[21,'mean'],2),' ± ', round(summary_shadow_mean[21,'sd']))`% sub-catchments having a net negative effect of all threats (see Figure SX and Table SX).

We investigated multi-species quantitative shadow distributions by calculating the percentage reduction in suitability predictions including threats compared to excluding threats (the expected suitability; Figure 5a-c). Across all sub-catchments, we found environmental suitability in the observed distribution was reduced by `r m3_shad[[4]]*100`% (averaged across species per sub-catchment = `r m3_shad[[2]]`) compared to the expected distribution (`r m3_shad[[1]]`; Figure 5a c.f. 5b; `r paste0('t = ', m3_shad[[3]])`). This average shadow distribution was spatially heterogenous (Figure 5d). Some large contiguous patches had lower than expected suitability, and the lowest 10^th^ quantile of catchments had an average suitability reduced by `r abs(m3_shad[[5]])*100`% (Figure 5c-d). Hiding beneath this average were also strong reductions in suitability for certain species within the expected assemblage (Figure 5e). As such, the most negatively impacted species in each sub-catchment had a environmental suitability reduction of `r abs(m3_shad[[6]])*100`% on average across sub-catchments (Figure 5e). The mean shadow distributions correlated negatively with both habitat quality and connectivity (Figure 5g-h; ρ = `r m3_shad[[8]]`; ρ = `r m3_shad[[7]]`) but less for minimum shadow distributions for habitat (ρ = `r m3_shad[[10]]`) than connectivity (ρ = `r m3_shad[[9]]`), indicating connectivity constraints defined the most negative impact within a community.When we simulated the alleviation of threats by turning environmental suitability contributions to 0, or to the mean contribution, we found reduced loss of environmental suitability (Figure SX-SX; Table SX) -- however the general spatial patterns were highly consistent.

**Figure S17.** Multi-species average shadow distribution properties per sub-catchment, for full description see Figure 6 of the main manuscript. Here we calculate shadow distributions turning any negative Shapley values for threats to 0 (see methods). To summarise the key results as in the main text for this method Across all sub-catchments, we found environmental suitability in the observed distribution was reduced by `r m1_shad[[4]]*100`% (averaged across species per sub-catchment = `r m3_shad[[2]]`) compared to the expected distribution (`r m1_shad[[1]]`;`r paste0('t = ', m1_shad[[3]])`). The lowest 10^th^ quantile of catchments had an average suitability reduced by `r abs(m1_shad[[5]])*100`%. The most negatively impacted species in each sub-catchment had a habitat suitability reduction of `r abs(m1_shad[[6]])*100`% on average across sub-catchments.

**Figure S17.** Multi-species average shadow distribution properties per sub-catchment, for full description see Figure 6 of the main manuscript. Here we calculate shadow distributions turning any negative Shapley values for threats to the mean positive contribution across all catchments (see methods). To summarise the key results as in the main text for this method Across all sub-catchments, we found environmental suitability in the observed distribution was reduced by `r m2_shad[[4]]*100`% (averaged across species per sub-catchment = `r m2_shad[[2]]`) compared to the expected distribution (`r m2_shad[[1]]`;`r paste0('t = ', m2_shad[[3]])`). The lowest 10^th^ quantile of catchments had an average suitability reduced by `r abs(m2_shad[[5]])*100`%. The most negatively impacted species in each sub-catchment had a habitat suitability reduction of `r abs(m2_shad[[6]])*100`% on average across sub-catchments.
